docker cp zhihang2025/standard_vtol drone:/root/PX4_Firmware/Tools/sitl_gazebo/models/
docker cp zhihang2025/iris_zhihang drone:/root/PX4_Firmware/Tools/sitl_gazebo/models/
docker cp zhihang2025/target_green drone:/root/PX4_Firmware/Tools/sitl_gazebo/models/
docker cp zhihang2025/landing2 drone:/root/PX4_Firmware/Tools/sitl_gazebo/models/
docker cp zhihang2025/person_standing drone:/root/.gazebo/models/
docker cp zhihang2025/zhihang2025.launch drone:/root/PX4_Firmware/launch/
docker cp zhihang2025/zhihang2025.world drone:/root/PX4_Firmware/Tools/sitl_gazebo/worlds/
docker cp zhihang2025/get_local_pose.py drone:/root/XTDrone/sensing/pose_ground_truth/
docker cp zhihang2025 drone:/root/XTDrone/