# YOLO11推理节点配置文件

# 模型配置
model:
  path: "models/yolo11n_original.pt"
  confidence_threshold: 0.6
  iou_threshold: 0.45

# 机型配置
aircraft:
  type: "standard_vtol"  # iris 或 standard_vtol
  
# 话题配置 (留空使用默认配置)
topics:
  input_image: ""
  output_image: ""
  pose: ""
  camera_info: ""

# 点云配置
pointcloud:
  enabled: true
  frame_id: "map"
  max_points_per_cloud: 1000
  publish_interval: 0.5  # 秒

# 相机变换参数（相机朝向正下方）
camera_transform:
  rotation_matrix: [[1, 0, 0], [0, 1, 0], [0, 0, -1]]
  translation: [0.0, 0.0, -0.03]

# 目标类别配置
target_classes:
  - "red"
  - "yellow"
  - "white"

# VTOL特殊配置
vtol:
  land_flag_topic: "/zhihang2025/vtol_land_sub/done"
  target_pose_topics:
    red: "/zhihang2025/first_man/pose"
    yellow: "/zhihang2025/second_man/pose"
    white: "/zhihang2025/third_man/pose"

# 调试配置
debug:
  log_level: "info"  # debug, info, warn, error
  enable_visualization: false
  save_detection_images: false
